-- ============================================
-- 1. ОЧИСТКА: Удаляем таблицы в правильном порядке
-- ============================================
--DROP TABLE IF EXISTS users CASCADE;
--DROP TABLE IF EXISTS categories CASCADE;
--DROP TABLE IF EXISTS events CASCADE;

-- ============================================
-- 2. СОЗДАНИЕ ТАБЛИЦ
-- ============================================

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

--Таблица категорий событий
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

--Таблица событий
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,  --название
    annotation VARCHAR(2000) NOT NULL, --Краткое описание
    category_id BIGINT NOT NULL, --    Категория
    confirmed_requests BIGINT, --Количество одобренных заявок на участие в данном событии
    created_on TIMESTAMP, --Дата и время создания события (в формате "yyyy-MM-dd HH:mm:ss")
    description VARCHAR(7000),  --Полное описание события
    event_date TIMESTAMP NOT NULL, --Дата и время на которые намечено событие (в формате "yyyy-MM-dd HH:mm:ss")
    initiator_id BIGINT NOT NULL, --    Пользователь (краткая информация)
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL, --    Широта и долгота места проведения события
    paid BOOLEAN NOT NULL, --Нужно ли оплачивать участие
    participant_limit BIGINT DEFAULT 0, --Ограничение на количество участников. Значение 0 - означает отсутствие ограничения
    published_on TIMESTAMP, --Дата и время публикации события (в формате "yyyy-MM-dd HH:mm:ss")
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,  --Нужна ли пре-модерация заявок на участие
    state VARCHAR(64) NOT NULL DEFAULT 'PENDING',  --Список состояний жизненного цикла события
    views BIGINT DEFAULT 0, --Количество просмотрев события
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_to_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_event_to_user FOREIGN KEY (initiator_id) REFERENCES users (id)
);