-- ============================================
-- 1. ОЧИСТКА: Удаляем таблицы в правильном порядке
-- ============================================
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilation_events CASCADE;

-- ============================================
-- 2. СОЗДАНИЕ ТАБЛИЦ
-- ============================================

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

--Таблица категорий событий
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

--Таблица событий
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,  --название
    annotation VARCHAR(2000) NOT NULL, --Краткое описание
    category_id BIGINT NOT NULL, --    Категория
    confirmed_requests BIGINT, --Количество одобренных заявок на участие в данном событии
    created_on TIMESTAMP, --Дата и время создания события (в формате "yyyy-MM-dd HH:mm:ss")
    description VARCHAR(7000),  --Полное описание события
    event_date TIMESTAMP NOT NULL, --Дата и время на которые намечено событие (в формате "yyyy-MM-dd HH:mm:ss")
    initiator_id BIGINT NOT NULL, --    Пользователь (краткая информация)
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL, --    Широта и долгота места проведения события
    paid BOOLEAN NOT NULL, --Нужно ли оплачивать участие
    participant_limit BIGINT DEFAULT 0, --Ограничение на количество участников. Значение 0 - означает отсутствие ограничения
    published_on TIMESTAMP, --Дата и время публикации события (в формате "yyyy-MM-dd HH:mm:ss")
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,  --Нужна ли пре-модерация заявок на участие
    state VARCHAR(64) NOT NULL DEFAULT 'PENDING',  --Список состояний жизненного цикла события
    views BIGINT DEFAULT 0, --Количество просмотрев события
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_to_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_event_to_user FOREIGN KEY (initiator_id) REFERENCES users (id)
);

--Таблица заявок на участие
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP,
    event BIGINT NOT NULL,
    requester BIGINT NOT NULL,
    status VARCHAR NOT NULL,
    CONSTRAINT uq_event_requester UNIQUE (event, requester),
    CONSTRAINT fk_request_to_event FOREIGN KEY (event) REFERENCES events (id),
    CONSTRAINT fk_request_to_user FOREIGN KEY (requester) REFERENCES users (id)
);

--Таблица подборок событий
CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT TRUE,
    title VARCHAR(50) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

--Таблица для связи событий и подборок событий
CREATE TABLE IF NOT EXISTS compilation_events (
 compilation_id BIGINT NOT NULL,
 event_id BIGINT NOT NULL,
 CONSTRAINT fk_compilation_events PRIMARY KEY (compilation_id, event_id),
 CONSTRAINT fk_compilation_events_to_compilations FOREIGN KEY(compilation_id) REFERENCES compilations(id),
 CONSTRAINT fk_compilation_events_to_events FOREIGN KEY(event_id) REFERENCES events(id)
);
